### ISSUE TITLE
Unable to Create Scanner Object using name Parameter in Python 3.x

### ISSUE THREAD

**Issue by trashgordon-zz** [openpaperwork/pyinsane#15]
I am using Python 3.4.0 with the following code (I have not tested with other minor versions):

```
import pyinsane.abstract as pyinsane
device = pyinsane.Scanner(name='epkowa:net:192.168.1.8')
```

This works in Python 2.7.6. However, I get the following error in Python 3.4.0:

```
AttributeError: 'str' object has no attribute 'decode'
```

I believe the str.decode() method was dropped in Python 3, which is why the error is getting thrown due to this line in the Scanner constructor:

```
self.name = name.decode('utf-8')
```

Since a string in Python 3 is already Unicode, perhaps there could just be a check on the parameters to see if they are already Unicode before attempting to decode them?
